
# Site settings
title: Zorrofoxline
email: null
description: > # this means to ignore newlines until "baseurl:"
  Zorrofoxline page
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zorrofoxline.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  zorrofoxline
